name: terragrunt-action
description: Terragrunt run Go action

inputs:
  arch:
    description: 'Architecture of the system (e.g. amd64, arm64)'
    default: amd64

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Run Go binary
      run: |
        echo "Architecture: ${{ inputs.arch }}"
        echo "$(ls)"
        chmod +x ./dist/${{ inputs.arch }}/terragrunt
        ./dist/${{ inputs.arch }}/terragrunt
      shell: bash