name: terragrunt-action
description: Terragrunt run Go action

inputs:
  arch:
    description: 'Architecture of the system (e.g. amd64, arm64)'
    default: amd64

runs:
  using: "composite"
  steps:
    - name: Checkout action
      uses: actions/checkout@v3
      with:
        repository: jvo5610/terragrunt-action
        ref: devel
        path: ./terragrunt-action
    - name: Run Go binary
      working-directory: ${{ github.workspace }}
      run: |
        echo "Architecture: ${{ inputs.arch }}"
        echo "$(ls)"
      shell: bash