name: terragrunt-action
description: Terragrunt run Go action

inputs:
  arch:
    description: 'Architecture of the system (e.g. amd64, arm64)'
    default: amd64
  github-token:
    description: 'GitHub Personal Access Token for accessing private repositories'
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        token: ${{ inputs.github-token }}
    - name: Run Go binary
      run: |
        echo "Binary path: ${{ inputs.binary-path }}"
        echo "GitHub workspace: $GITHUB_WORKSPACE"
        echo "Architecture: ${{ inputs.arch }}"
        cd $GITHUB_WORKSPACE
        chmod +x dist/${{ inputs.arch }}/terragrunt
        ./dist/${{ inputs.arch }}/terragrunt